### ISSUE TITLE
Controle e Física

### ISSUE THREAD

**Issue by LeoTSantos** [LeoTSantos/Pingmatronix#4]
Construção do controlador geral de física

**Comment by pauloludewig** [comment]
RECEBE:
START
PAUSE
POSICAO_A
POSICAO_B
BOTAO_MISSIL_A
BOTAO_MISSIL_B

RETORNA:
POSICAO_MISSIL_A
POSICAO_MISSIL_B
POSICAO_BOLA
PONTOS_A
PONTOS_B
SAIDAS PARA SOM: REBATEU, PONTO
SAIDAS PARA LED: PONTO, MISSIL_ACERTOU
