### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by LeoTSantos** [LeoTSantos/Pingmatronix#5]
Documentar o projeto:
- Fotos
- Esquematico
- Diagrama de arquitetura

**Comment by massaAMN** [comment]
[PONG - Pingmatronix.docx](https://github.com/LeoTSantos/Pingmatronix/files/1435083/PONG.-.Pingmatronix.docx)

**Comment by massaAMN** [comment]
[PONG - Pingmatronix.docx](https://github.com/LeoTSantos/Pingmatronix/files/1435206/PONG.-.Pingmatronix.docx)

**Comment by massaAMN** [comment]
[PONG.-.Pingmatronix.docx](https://github.com/LeoTSantos/Pingmatronix/files/1546316/PONG.-.Pingmatronix.docx)

**Comment by massaAMN** [comment]
[PONG.-.Pingmatronix.docx](https://github.com/LeoTSantos/Pingmatronix/files/1547852/PONG.-.Pingmatronix.docx)

**Comment by massaAMN** [comment]
[PONG.-.Pingmatronix.docx](https://github.com/LeoTSantos/Pingmatronix/files/1551482/PONG.-.Pingmatronix.docx)

**Comment by massaAMN** [comment]
[PONG.-.Pingmatronix.docx](https://github.com/LeoTSantos/Pingmatronix/files/1553647/PONG.-.Pingmatronix.docx)

**Comment by massaAMN** [comment]
[PONG - Pingmatronix.docx](https://github.com/LeoTSantos/Pingmatronix/files/1556647/PONG.-.Pingmatronix.docx)

**Comment by massaAMN** [comment]
[PONG - PingMatronix.pdf](https://github.com/LeoTSantos/Pingmatronix/files/1556655/PONG.-.PingMatronix.pdf)
